---

- name: Include version-specific variables
  include_vars: "kibana-{{ kibana_repo_version }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Ensure kibana log dir exists with right permissions
  file:
    dest: "{{ kibana_logging_dest | dirname }}"
    state: directory
    owner: kibana

# - name: Ensure acl package is present
#   package: name=acl state=present
#
### FIXME! not idempotent on older distributions (centos6, trusty, precise)
# - name: Ensure kibana log dir has right permissions with acl
#   acl:
#     name: "{{ kibana_logging_dest | dirname }}"
#     entity: kibana
#     etype: user
#     permissions: "rwx"
#     state: present
