---
- name: Ensure dependency is installed (Ubuntu).
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - acl

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
    state: present
    update_cache: true
